
/**
 * This script has all the prompt builders generated by AI.
 *
 */
// module.exports = {
//   buildPrompt: function (prompt) {
export function buildPrompt(prompt) {
  const category = prompt.category;
  switch (category) {
    case 'ActBasic':
    case 'ActManual':
    case 'ActPhysical':
    case 'ActSocial':
      return buildPromptActivity(prompt);
    case 'Animal':
      return buildPromptAnimal(prompt);
    case 'Causative':
      return buildPromptCausativeVerb(prompt);
    case 'Body':
      return buildPromptBody(prompt);
    case 'Building':
      return buildPromptBuilding(prompt);
    case 'Clothing':
      return buildPromptClothing(prompt);
    case 'Color':
      return buildPromptColor(prompt);
    case 'Communication':
      return buildPromptCommunication(prompt);
    case 'Culture':
      return buildPromptCulture(prompt);
    case 'DateTime':
      return buildPromptDateTime(prompt);
    case 'Degree':
      return buildPromptDegree(prompt);
    case 'Direction':
      return buildPromptDirection(prompt);
    case 'Emotion':
      return buildPromptEmotion(prompt);
    case 'Evaluative':
      return buildPromptEvaluative(prompt);
    case 'Existence':
      return buildPromptExistence(prompt);
    case 'Family':
      return buildPromptFamily(prompt);
    case 'Food':
      return buildPromptFood(prompt);
    case 'Frequency':
      return buildPromptFrequency(prompt);
    case 'Fruit':
      return buildPromptFruit(prompt);
    case 'Furniture':
      return buildPromptFurniture(prompt);
    case 'Health':
      return buildPromptHealth(prompt);
    case 'Home':
      return buildPromptHome(prompt);
    case 'Mental':
      return buildPromptMental(prompt);
    case 'Metal':
      return buildPromptMetal(prompt);
    case 'Money':
      return buildPromptMoney(prompt);
    case 'Motion':
      return buildPromptMotion(prompt);
    case 'Nature':
      return buildPromptNature(prompt);
    case 'Noun':
      return buildPromptNoun(prompt);
    case 'Number':
      return buildPromptNumber(prompt);
    case 'People':
      return buildPromptPeople(prompt);
    case 'Place':
      return buildPromptPlace(prompt);
    case 'Plant':
      return buildPromptPlant(prompt);
    case 'Quantitative':
      return buildPromptQuantitative(prompt);
    case 'School':
      return buildPromptSchool(prompt);
    case 'Relational':
      return buildPromptRelational(prompt);
    case 'Possession':
      return buildPromptPossession(prompt);
    case 'SetDenoting':
      return buildPromptSetDenoting(prompt);
    case 'Stationery':
      return buildPromptStationery(prompt);
    case 'Shape':
      return buildPromptShape(prompt);
    case 'Toiletry':
      return buildPromptToiletry(prompt);
    case 'Tool':
      return buildPromptTool(prompt);
    case 'Toy':
      return buildPromptToy(prompt);
    case 'Stative':
      return buildPromptStative(prompt);
    case 'Tableware':
      return buildPromptTableware(prompt);
    case 'Verb':
      return buildPromptVerb(prompt);
    case 'Weapon':
      return buildPromptWeapon(prompt);
    case 'Vegetable':
      return buildPromptVegetable(prompt);
    case 'Vehicle':
      return buildPromptVehicle(prompt);
    case 'Time':
    case 'Certainty':
    case 'Conjunction':
    case 'MeasureWord':
    case 'Negation':
    case 'Particle':
    case 'Preposition':
    case 'Pronoun':
      return buildPromptFunctionalGroup(p);
    default:
      console.error(`未知类别: ${category}`);
      return 'unknown';
  }
}

const NO_TEXT = 'No English text, no Chinese characters, no letters, no numbers, no symbols in the image, no any kind of frame. A simple background. ';
const BACKGROUND_SIMPLE = '一个简单的正方形图示。'
const BACKGROUND_FAMILY = '一个简单的正方形图示，背景为现代中国城市家庭场景。';
const BACKGROUND_FIELD = '一个简单的正方形图示，背景为空旷的田野。'
const BACKGROUND_STREET = '一个简单的正方形图示，背景为海洋、湖泊或者城市的街道或天空。图中的交通工具都是现代的交通工具。'
const BACKGROUND_SCHOOL = '一个简单的正方形图示，背景为学校教室或操场。'
const BACKGROUND_OUTDOOR = '一个简单的正方形图示，背景为户外。'
const BACKGROUND_FOREST = '一个简单的正方形图示，背景为森林或草原。';


// 功能性字组 Symbol 生成函数
function buildPromptFunctionalGroup(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张摄影画，${p.action}.`;
}

// Verb 一般动词组（摄影风格的水彩画，人物 5-9 岁）
function buildPromptVerb(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。`;
}

// Weapon 武器组（摄影画，无人物，武器）
function buildPromptWeapon(p) {
  return `${NO_TEXT} ${BACKGROUND_FIELD} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Vegetable 蔬菜组（摄影画，无人物，蔬菜）
function buildPromptVegetable(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Vehicle 交通工具组（摄影画，无人物，交通工具）
function buildPromptVehicle(p) {
  return `${NO_TEXT} ${BACKGROUND_STREET} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Toiletry 洗漱组（摄影画，无人物，洗漱用品）
function buildPromptToiletry(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Tool 工具组（摄影画，无人物，典型工具）
function buildPromptTool(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Toy 玩具组（摄影画，无人物，典型玩具）
function buildPromptToy(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Stative 状态组（摄影风格的水彩画，人物 25-40 岁）
function buildPromptStative(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}人，穿着${p.dress}，${p.addStyle}。`;
}

// Tableware 餐具组（摄影画，无人物，典型餐具）
function buildPromptTableware(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Shape 形状组（摄影画，无人物，用事物表示形状）
function buildPromptShape(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Stationery 文具组（摄影画，无人物，用典型文具表示文具）
function buildPromptStationery(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// SetDenoting 类属组（摄影画，无人物，用事物说明类属现象）
function buildPromptSetDenoting(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// School 学校组（摄影风格的水彩画，人物 6-10 岁）
function buildPromptSchool(p) {
  return `${NO_TEXT} ${BACKGROUND_SCHOOL} 为“${p.character}”字画一张${p.sceneStyle}, 展示了学校生活, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。简单的背景.`;
}

// Relational 关系组（摄影画，无人物，用事物说明关系）
function buildPromptRelational(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Possession 拥有组（摄影风格的水彩画，人物 30-40 岁）
function buildPromptPossession(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}人，穿着${p.dress}，${p.addStyle}。简单的背景.`;
}

// Place 地点组（摄影画，无人物，地点）
function buildPromptPlace(p) {
  return `${NO_TEXT} ${BACKGROUND_OUTDOOR} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Plant 植物组（摄影画，无人物，植物）
function buildPromptPlant(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Quantitative 数量组（摄影画，无人物，数量表现）
function buildPromptQuantitative(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Number 数字组（卡通画，有人物作陪衬，突出拟人化数字）
function buildPromptNumber(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 为“${p.character}”字画一张${p.sceneStyle}, 突出展示这个拟人化的阿拉伯数字， ${p.age}岁、作为陪衬的人物在画面中不要占太多的地方。简单的背景，square format.`;
}

// People 人物组（卡通画，不同身份的拟人化人物）
function buildPromptPeople(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 突出展示这个不同身份的人物， ${p.age}岁。`;
}

// Nature 自然组（摄影画，无人物，自然景色）
function buildPromptNature(p) {
  return `${NO_TEXT} ${BACKGROUND_OUTDOOR} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Noun 一般名词组（摄影画，无人物，具体实物）
function buildPromptNoun(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Money 金钱组（摄影画，无人物，典型制品）
function buildPromptMoney(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Motion 移动动词组（摄影风格的水彩画，有人物）
function buildPromptMotion(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。`;
}

// Mental 心理动词组（摄影风格的水彩画，有人物）
function buildPromptMental(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY}。 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。`;
}

// Metal 金属组（摄影画，无人物，强隐喻场景）
function buildPromptMetal(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Fruit 水果组
function buildPromptFruit(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Furniture 家具组
function buildPromptFurniture(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Health 健康组
function buildPromptHealth(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Home 家居组
function buildPromptHome(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Evaluative 评价组（抽象-评价，中国画，人物表情+场景）
function buildPromptEvaluative(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}，图中的人物为现代城市居民。`;
}

// Existence 存在组（抽象-存在，中国画，人物表情+场景）
function buildPromptExistence(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}，图中的人物为现代城市居民。`;
}

// Family 家庭组
function buildPromptFamily(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}，图中的人物为现代城市居民。`;
}

// Frequency 频率组
function buildPromptFrequency(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Emotion 情感组（抽象-情感，无任务句 + 强隐喻场景）
function buildPromptEmotion(p) {
 return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}.`;
}

// Degree 时间组
function buildPromptDateTime(p) {
 return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}。`;
}

// Degree 程度组
function buildPromptDegree(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}。`;
}

// Direction 方向组
function buildPromptDirection(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 画一张${p.sceneStyle}, ${p.action}。`;
}

// Culture 文化组，人物 3-6 岁
function buildPromptCulture(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 表现了这个文化符号, ${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。`;
}

// Animal 动物组（无人物版，国画风格水彩画）
function buildPromptAnimal(p) {
  return `${NO_TEXT} ${BACKGROUND_FOREST} 为“${p.character}”字画一张${p.sceneStyle}, 表现了${p.addStyle}，${p.action}。`;
}

// Food 食物组（无人物版）
function buildPromptFood(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 表现了${p.addStyle}，${p.action}。`;
}

// Causative 使动词组（有人物版，人物 6-8 岁）
function buildPromptCausativeVerb(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张摄影画, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.action}。`;
}

// Activity 行为动词组（国画风格的水彩画，有人物，人物 4-8 岁，展示动作）
function buildPromptActivity(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张摄影画, 展示了这个动词的动作, ${p.age}岁、${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.action}。`
}

// Body 身体组（有人物作陪衬，突出身体部位）
function buildPromptBody(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 突出展示这个身体部位，比如嘴、眼、手等, ${p.action}、作为陪衬的人物在画面中不要占太多的地方。`
}

// Building 建筑组（有人物远处作陪衬，突出建筑）
function buildPromptBuilding(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 突出展示这个建筑，比如桥、坛、堂等, ${p.action}、作为陪衬的人物在画面中不要占太多的地方。`
}

// Clothing 衣物组（无人物，突出衣物）
function buildPromptClothing(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 为“${p.character}”字画一张${p.sceneStyle}, 突出展示这件衣物，比如衣服、帽子，裙子等。`
}

// Color 颜色组（有人物，物品表现颜色）
function buildPromptColor(p) {
  return `${NO_TEXT} ${BACKGROUND_SIMPLE} 为“${p.character}”字画一张${p.sceneStyle}, 展示这种颜色等。`
}

// Communication 交流动词组
function buildPromptCommunication(p) {
  return `${NO_TEXT} ${BACKGROUND_FAMILY} 为“${p.character}”字画一张${p.sceneStyle}, 展示了这个动词的动作, ${p.personality}的现代中国${p.sex}孩，穿着${p.dress}，${p.addStyle}。`;
}
