
/**
 * This script is a one-off script that does 2 things:
 * 1 - updates the json-prompts/activity.json, collection/all-words.json with the ActivityVerbs.
 * 2 - Updates the category field of all the JSON files in the json-prompts folder to use English name. 
 * 
 * The JSON files are generated by 腾讯混元 AI at https://hunyuan.tencent.com
 *
 * Usage: node prompt-update.js
 */
import fs from 'fs';
import path from 'path';

// configurations
const jsonFileDir = 'json-prompts';
const jsonFileDirUpdate = 'json-prompts-update';
const origWordsFile = './collection/all-words.json';
const updatedWordsFile = './collection/all-words-update.json';
const origActivityFile = './json-prompts/activity.json';
const updatedActivityFile = './json-prompts/activity-update.json';
const ActivityVerbs = [
  {
    "category": "ActBasic", "characters": [
      "做", "写", "动", "吃", "喝", "睡", "脱", "穿", "洗", "梳", "玩", "看", "走", "停", "开", "拉", "推", "完", "打", "扔", "找", "排", "敲", "流", "碰", "离", "端", "练", "歇", "献", "陪", "入", "吞", "托", "护", "招", "止", "泡", "炒", "煮", "熨", "犯", "磨", "织", "藏", "铺", "闭", "充", "凑", "削", "剥", "割", "劈", "勾", "叠", "叼", "吻", "咽", "啃", "喘", "嚼", "寻", "屯", "延", "扛", "除", "扮", "抹", "担", "拌", "拎", "拣", "拦", "拧", "拨", "拱", "拴", "拽", "持", "挎", "挠", "敬", "敷", "删"]
  },
  {
    "category": "ActManual", "characters": [
      "建", "加", "抓", "按", "放", "敢", "演", "照", "查", "补", "订", "调", "晾", "试", "冲", "切", "剪", "吐", "吹", "咬", "咳", "喷", "夹", "射", "戒", "扶", "抄", "披", "抬", "拆", "拍", "拔", "拼", "挡", "挤", "插", "握", "搞", "埋", "奏", "凿", "创", "摆", "摇", "摘", "支", "救", "晒", "漏", "绕", "装", "躲", "钓", "作", "刮", "刺", "吊", "扣", "拖", "挨", "捉", "捕", "撑", "束", "灭", "勒", "煎", "蒸", "裁", "裹", "扩", "扒", "扳", "拄", "抠", "剃", "扯", "刨", "制", "挖", "掏", "举"]
  },
  {
    "category": "ActPhysical", "characters": [
      "跑", "跳", "爬", "倒", "踢", "踩", "跨", "钻", "翻", "扑", "扭", "晃", "甩", "蹦", "蹬", "跃", "奔", "追", "闪", "闹", "抖", "抛", "抡", "挥", "挽", "捂", "捅", "捆", "捏", "捶", "掀", "掐", "揉", "揪", "搀", "搁", "摊", "撇", "撤", "撬", "攻", "斗", "斩", "映", "曰", "栽", "榨", "沏", "沾", "注", "浇", "涂", "涮", "淋", "淌", "淘", "溢", "灌", "炖", "熏", "熬", "盗", "砍", "砸", "磕", "积", "筑", "筛", "经", "绑", "绞", "绣", "置", "舔", "葬", "逮", "遮", "干", "弄", "刻", "压", "挂", "指"]
  },
  {
    "category": "ActSocial", "characters": [
      "帮", "办", "问", "求", "教", "让", "使", "合", "连", "集", "顾", "遇", "避", "醒", "骗", "邀", "赌", "据", "负", "劫", "采", "销", "镶", "附", "陷", "雕", "震", "驮", "驾", "验", "争", "辩", "劝", "谢", "骂", "夸", "罚", "奖", "选", "通", "用", "赶", "造", "配", "防", "领", "证", "修", "划", "吸", "处", "守", "当", "扫", "投", "抱", "抽", "挑", "散", "替", "汇", "治", "测", "赖", "逼", "破", "租", "移", "等", "结", "聚", "贴", "赢", "隔", "许", "设", "征", "豁", "赴", "蹭", "辞", "逗", "逢", "蒙"]
  }
];

/**
 * Updates the category field of all the JSON files in the json-prompts folder to use English name. 
 */
function updatePrompts() {

  // Re-create an empty json-prompts-update directory
  fs.rmSync(jsonFileDirUpdate, { recursive: true, force: true });
  fs.mkdirSync(jsonFileDirUpdate, { recursive: true });
  console.log(`Directory is deleted and re-created: ${jsonFileDirUpdate}`);

  // const jsonWords = fs.readFileSync(origWordsFile, 'utf8');
  // const words = JSON.parse(jsonWords);

  const allChars = [];
  try {
    const files = fs.readdirSync(jsonFileDir);
    files.forEach(file => {
      const jsonFile = jsonFileDir + '/' + file;
      console.log('Processing:', jsonFile);
      const chars = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));
      allChars.push(...chars);
    })
  }
  catch (error) {
    console.error('Processing failed', error);
  }

  const sortedChars = allChars.sort((a, b) => {
    return a.category.localeCompare(b.category);
  });

  const categorized = {};

  // Group the words by category and level
  for (const char of sortedChars) {
    const key = char.category;
    if (!categorized[key]) {
      categorized[key] = [];
    }
    categorized[key].push(char);
  }

  const sortedEntries = Object.fromEntries(
    Object.entries(categorized).sort(([keyA], [keyB]) => keyA.localeCompare(keyB))
  );
  // console.log(sortedEntries);


  // Write each category to its own file
  let wordCount = 0;
  for (const key of Object.keys(sortedEntries)) {
    const fileName = `${key}.json`;
    const filePath = path.join(jsonFileDirUpdate, fileName);
    let json = JSON.stringify(sortedEntries[key]);
    json = json.replaceAll('},{', '},\n{');

    fs.writeFileSync(filePath, json, 'utf-8');
    console.log(`Created: ${fileName}`);
    wordCount += sortedEntries[key].length;
  }
}

/**
 * Updates the category field of all the JSON files in the json-prompts folder to use English name. 
 */
function updateCategories() {
  // Delete the directory and all its contents recursively
  fs.rmSync(jsonFileDirUpdate, { recursive: true, force: true });

  // Re-create the empty directory
  fs.mkdirSync(jsonFileDirUpdate, { recursive: true });
  console.log(`Directory is deleted and re-created: ${jsonFileDirUpdate}`);

  const jsonWords = fs.readFileSync(origWordsFile, 'utf8');
  const words = JSON.parse(jsonWords);
  try {
    const files = fs.readdirSync(jsonFileDir);
    files.forEach(file => {
      const jsonFile = jsonFileDir + '/' + file;
      console.log('Processing:', jsonFile);
      const chars = JSON.parse(fs.readFileSync(jsonFile, 'utf8'));
      for (const char of chars) {
        const word = words.find(w => w.chinese == char.character);
        if (word) {
          char.category = word.category;
        }
      }
      const sortedChars = chars.sort((a, b) => {
        return a.category.localeCompare(b.category);
      });
      const updatedFile = jsonFileDirUpdate + '/' + file;
      const updatedChars = JSON.stringify(sortedChars, null, 2);
      fs.writeFileSync(updatedFile, updatedChars, 'utf-8');
      console.log(`Created a prompt file: ${file}`);
    })
  }
  catch (error) {
    console.error('Processing failed', error);
  }
}

/**
 * Updates the category field of the all-words.json and activiy.json 
 * to split Activity into ActBasic, ActManual, ActPhysical and ActSocial 
 */
function updateActivityCategory() {
  const jsonWords = fs.readFileSync(origWordsFile, 'utf8');
  const words = JSON.parse(jsonWords);
  console.log('Processing:', origWordsFile);
  try {
    for (const word of words) {
      const category = findNewCategory(word);
      word.category = category;
      word.image = category + '/' + word.chinese + '.png';
    }
    const sortedWords = words.sort((a, b) => {
      return a.category.localeCompare(b.category);
    });

    const updatedWords = JSON.stringify(sortedWords, null, 2);
    fs.writeFileSync(updatedWordsFile, updatedWords, 'utf-8');
    console.log(`🎉 Finished updating merged-word.json.\n`);
  }
  catch (error) {
    console.error('Updating merged-word.json failed', error);
  }

  const jsonChars = fs.readFileSync(origActivityFile, 'utf8');
  const chars = JSON.parse(jsonChars);
  console.log('Processing:', origActivityFile);
  try {
    for (const char of chars) {
      const category = findNewCategory(char);
      char.category = category;
    }
    const sortedChars = chars.sort((a, b) => {
      return a.category.localeCompare(b.category);
    });
    const updatedActivities = JSON.stringify(sortedChars, null, 2);
    fs.writeFileSync(updatedActivityFile, updatedActivities, 'utf-8');
    console.log(`🎉 Finished updating activity.json.\n`);
  }
  catch (error) {
    console.error('Updating activity.json failed', error);
  }
}

function findNewCategory(word) {
  let character = (Object.hasOwn(word, "chinese") ? word.chinese : word.character);
  for (const category of ActivityVerbs) {
    if (category.characters.find(c => c == character)) {
      return category.category;
    }
  }
  return word.category;
}

updatePrompts()
